// Pure adapter checks. Node VM fakes only; no Apple events or real terminals.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('Resources/iterm.js', 'utf8');
const session = {id:()=> 'fixture-session', tty:()=> '/dev/fixture', name:()=> 'Fallback'};
let selected = 0, closed = 0, title = 'Task title';
let bounds = {x:80,y:60,width:900,height:600};
const tab = {sessions:()=>[session]};
Object.defineProperty(tab, 'title', {get:()=>()=>title, set:v=>title=v});
const live = {id:()=>1, name:()=> 'Fixture', tabs:()=>[tab], select:()=>selected++, close:()=>closed++};
Object.defineProperty(live, 'bounds', {get:()=>()=>bounds, set:v=>bounds=v});
const undo = {id:()=>2, name:()=> 'Retained closed window', tabs:()=>null};
const app = {running:()=>true, windows:()=>[undo,live], activate:()=>{}};
const frame = {origin:{x:0,y:0},size:{width:1440,height:900}};
const visibleFrame = {origin:{x:0,y:25},size:{width:1440,height:850}};
const context = vm.createContext({Application:()=>app, ObjC:{import:()=>{}},
    $:{NSScreen:{screens:{count:1,objectAtIndex:()=>({frame,visibleFrame})}}}});
vm.runInContext(source,context);
function call(request){return JSON.parse(context.run([JSON.stringify(request)]));}
const rows=call({action:'list'});
assert.equal(rows.length,1);assert.equal(rows[0].id,'1');
assert.deepEqual(rows[0].bounds,bounds);
assert.equal(rows[0].tabs[0].sessions[0].title,'Task title');
assert.throws(()=>call({action:'close',windowId:'2',sessionIds:['fixture-session']}));
assert.throws(()=>call({action:'close',windowId:'1',sessionIds:['wrong-session']}));
assert.equal(closed,0);
call({action:'focus',windowId:'1',sessionIds:['fixture-session']});assert.equal(selected,1);
call({action:'close',windowId:'1',sessionIds:['fixture-session']});assert.equal(closed,1);
assert.equal(selected,2);
const savedTitle = '🚙 Notes "quoted" / $(not a command)';
call({action:'set-title',windowId:'1',sessionId:'fixture-session',title:savedTitle});
assert.equal(title,savedTitle);
assert.throws(()=>call({action:'set-title',windowId:'1',sessionId:'wrong',title:'Wrong tab'}));
assert.equal(title,savedTitle);
call({action:'set-bounds',windowId:'1',sessionIds:['fixture-session'],bounds:{x:40,y:45,width:800,height:550}});
assert.deepEqual(JSON.parse(JSON.stringify(bounds)),{x:40,y:45,width:800,height:550});
call({action:'set-bounds',windowId:'1',sessionIds:['fixture-session'],bounds:{x:5000,y:-3000,width:2000,height:1800}});
assert.deepEqual(JSON.parse(JSON.stringify(bounds)),{x:0,y:25,width:1440,height:850});
assert.throws(()=>call({action:'set-bounds',windowId:'1',sessionIds:['wrong'],bounds:{x:0,y:0,width:800,height:500}}));
assert.throws(()=>call({action:'set-bounds',windowId:'1',sessionIds:['fixture-session'],bounds:{x:0,y:0,width:-1,height:500}}));
console.log('JXA checks passed: exact targeting, title restoration, geometry and disconnected-display clamping.');
